version: '3.8'

services:
  db:
    image: postgres:16.3
    container_name: postgres-db
    environment:
      POSTGRES_DB: social
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./scripts/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "5433:5432"
    restart: unless-stopped

  app:
    build: .
    container_name: social-app
    environment:
      - DB_ADDR=host=db port=5432 user=postgres password=${DB_PASSWORD} dbname=social sslmode=disable
      - ADDR=:8081
    ports:
      - "8081:8081"
    depends_on:
      - db
    restart: unless-stopped

volumes:
  db-data: 